# Generated by Django 6.0.2 on 2026-02-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id_card_image',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
